# Configuration file
# key = value


quarkus:
  http:
    auth:
      form:
        cookie-name: StoreCardCookie

  #datasource settings
  datasource:
    url: vertx-reactive:postgresql://localhost:5432/main_postgres_db
    username: ${QUARKUS_DATASOURCE_USERNAME}
    password: ${QUARKUS_DATASOURCE_PASSWORD}

#locale
default-locale: pl-PL

com:
  example:
    default-locale: pl
    elasticsearch-host: localhost
    elasticsearch-port: 9200
