CREATE SEQUENCE address_id_seq
       INCREMENT BY 1
       MINVALUE 1
       CACHE 1
       NO CYCLE;

CREATE SEQUENCE category_id_seq
       INCREMENT BY 1
       MINVALUE 1
       CACHE 1
       NO CYCLE;

CREATE SEQUENCE categorydetails_id_seq
       INCREMENT BY 1
       MINVALUE 1
       CACHE 1
       NO CYCLE;

CREATE SEQUENCE image_id_seq
       INCREMENT BY 1
       MINVALUE 1
       CACHE 1
       NO CYCLE;

CREATE SEQUENCE item_id_seq
       INCREMENT BY 1
       MINVALUE 1
       CACHE 1
       NO CYCLE;

CREATE SEQUENCE itemdetails_id_seq
       INCREMENT BY 1
       MINVALUE 1
       CACHE 1
       NO CYCLE;

CREATE SEQUENCE itemquantity_id_seq
       INCREMENT BY 1
       MINVALUE 1
       CACHE 1
       NO CYCLE;

CREATE SEQUENCE orderdetails_id_seq
       INCREMENT BY 1
       MINVALUE 1
       CACHE 1
       NO CYCLE;

CREATE SEQUENCE producer_id_seq
       INCREMENT BY 1
       MINVALUE 1
       CACHE 1
       NO CYCLE;

CREATE SEQUENCE producerdetails_id_seq
       INCREMENT BY 1
       MINVALUE 1
       CACHE 1
       NO CYCLE;

CREATE SEQUENCE userentity_id_seq
       INCREMENT BY 1
       MINVALUE 1
       CACHE 1
       NO CYCLE;

CREATE TABLE IF NOT EXISTS address
(
   id       bigint         GENERATED BY DEFAULT AS IDENTITY (MAXVALUE 9223372036854775807),
   city     varchar(255),
   local    varchar(255),
   street   varchar(255),
   zip      varchar(255),
   user_id  bigint
);

-- Column id is associated with sequence public.address_id_seq

ALTER TABLE address
   ADD CONSTRAINT address_pkey
   PRIMARY KEY (id);

CREATE TABLE IF NOT EXISTS category
(
   id  bigint   GENERATED BY DEFAULT AS IDENTITY (MAXVALUE 9223372036854775807)
);

-- Column id is associated with sequence public.category_id_seq

ALTER TABLE category
   ADD CONSTRAINT category_pkey
   PRIMARY KEY (id);

CREATE TABLE IF NOT EXISTS categorydetails
(
   id           bigint         GENERATED BY DEFAULT AS IDENTITY (MAXVALUE 9223372036854775807),
   description  varchar(255),
   lang         varchar(255),
   name         varchar(255),
   category_id  bigint
);

-- Column id is associated with sequence public.categorydetails_id_seq

ALTER TABLE categorydetails
   ADD CONSTRAINT categorydetails_pkey
   PRIMARY KEY (id);

CREATE TABLE IF NOT EXISTS image
(
   id   bigint         GENERATED BY DEFAULT AS IDENTITY (MAXVALUE 9223372036854775807),
   alt  varchar(255),
   url  varchar(255)
);

-- Column id is associated with sequence public.image_id_seq

ALTER TABLE image
   ADD CONSTRAINT image_pkey
   PRIMARY KEY (id);

CREATE TABLE IF NOT EXISTS item
(
   id           bigint          GENERATED BY DEFAULT AS IDENTITY (MAXVALUE 9223372036854775807),
   stock        integer         NOT NULL,
   valuegross   numeric(19,2),
   vat          float8          NOT NULL,
   image_id     bigint,
   producer_id  bigint
);

-- Column id is associated with sequence public.item_id_seq

ALTER TABLE item
   ADD CONSTRAINT item_pkey
   PRIMARY KEY (id);

CREATE TABLE IF NOT EXISTS item_category
(
   item_id      bigint   NOT NULL,
   category_id  bigint   NOT NULL
);

ALTER TABLE item_category
   ADD CONSTRAINT item_category_pkey
   PRIMARY KEY (item_id, category_id);

CREATE TABLE IF NOT EXISTS item_producer
(
   item_id      bigint   NOT NULL,
   producer_id  bigint   NOT NULL
);

ALTER TABLE item_producer
   ADD CONSTRAINT item_producer_pkey
   PRIMARY KEY (item_id, producer_id);

CREATE TABLE IF NOT EXISTS itemdetails
(
   id           bigint         GENERATED BY DEFAULT AS IDENTITY (MAXVALUE 9223372036854775807),
   description  text,
   lang         varchar(255),
   name         varchar(255),
   item_id      bigint
);

-- Column id is associated with sequence public.itemdetails_id_seq

ALTER TABLE itemdetails
   ADD CONSTRAINT itemdetails_pkey
   PRIMARY KEY (id);

CREATE TABLE IF NOT EXISTS itemdetails_image
(
   itemdetails_id  bigint   NOT NULL,
   images_id       bigint   NOT NULL
);

ALTER TABLE itemdetails_image
   ADD CONSTRAINT itemdetails_image_pkey
   PRIMARY KEY (itemdetails_id, images_id);

ALTER TABLE itemdetails_image
   ADD CONSTRAINT uk_d2y1g5igcxbitt9wso7t98j13 UNIQUE (images_id);



CREATE TABLE IF NOT EXISTS itemquantity
(
   id               bigint    GENERATED BY DEFAULT AS IDENTITY (MAXVALUE 9223372036854775807),
   amount           integer   NOT NULL,
   item_id          bigint,
   orderdetails_id  bigint
);

-- Column id is associated with sequence public.itemquantity_id_seq

ALTER TABLE itemquantity
   ADD CONSTRAINT itemquantity_pkey
   PRIMARY KEY (id);

CREATE TABLE IF NOT EXISTS orderdetails
(
   id             bigint         GENERATED BY DEFAULT AS IDENTITY (MAXVALUE 9223372036854775807),
   creationdate   date,
   orderstatus    varchar(255),
   paymentmethod  varchar(255),
   paymentstatus  varchar(255),
   address_id     bigint,
   userentity_id  bigint
);

-- Column id is associated with sequence public.orderdetails_id_seq

ALTER TABLE orderdetails
   ADD CONSTRAINT orderdetails_pkey
   PRIMARY KEY (id);

CREATE TABLE IF NOT EXISTS producer
(
   id        bigint   GENERATED BY DEFAULT AS IDENTITY (MAXVALUE 9223372036854775807),
   image_id  bigint
);

-- Column id is associated with sequence public.producer_id_seq

ALTER TABLE producer
   ADD CONSTRAINT producer_pkey
   PRIMARY KEY (id);

CREATE TABLE IF NOT EXISTS producerdetails
(
   id           bigint         GENERATED BY DEFAULT AS IDENTITY (MAXVALUE 9223372036854775807),
   description  varchar(255),
   lang         varchar(255),
   name         varchar(255),
   producer_id  bigint
);

-- Column id is associated with sequence public.producerdetails_id_seq

ALTER TABLE producerdetails
   ADD CONSTRAINT producerdetails_pkey
   PRIMARY KEY (id);

CREATE TABLE IF NOT EXISTS userentity
(
   id         bigint         GENERATED BY DEFAULT AS IDENTITY (MAXVALUE 9223372036854775807),
   email      varchar(255),
   firstname  varchar(255),
   lastname   varchar(255)
);

-- Column id is associated with sequence public.userentity_id_seq

ALTER TABLE userentity
   ADD CONSTRAINT userentity_pkey
   PRIMARY KEY (id);

CREATE TABLE IF NOT EXISTS userentity_permissions
(
   userentity_id  bigint         NOT NULL,
   permissions    varchar(255)
);

ALTER SEQUENCE address_id_seq OWNED BY address.id;
ALTER SEQUENCE category_id_seq OWNED BY category.id;
ALTER SEQUENCE categorydetails_id_seq OWNED BY categorydetails.id;
ALTER SEQUENCE image_id_seq OWNED BY image.id;
ALTER SEQUENCE item_id_seq OWNED BY item.id;
ALTER SEQUENCE itemdetails_id_seq OWNED BY itemdetails.id;
ALTER SEQUENCE itemquantity_id_seq OWNED BY itemquantity.id;
ALTER SEQUENCE orderdetails_id_seq OWNED BY orderdetails.id;
ALTER SEQUENCE producer_id_seq OWNED BY producer.id;
ALTER SEQUENCE producerdetails_id_seq OWNED BY producerdetails.id;
ALTER SEQUENCE userentity_id_seq OWNED BY userentity.id;


ALTER TABLE address
  ADD CONSTRAINT fk7xwr01ggh9t1nudtn7nyeiq17 FOREIGN KEY (user_id)
  REFERENCES userentity (id)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE categorydetails
  ADD CONSTRAINT fkq814ig8rkfqav40q4l43qc6yp FOREIGN KEY (category_id)
  REFERENCES category (id)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE item
  ADD CONSTRAINT fkr3q9b86cnpfnveexfr4iaefrg FOREIGN KEY (image_id)
  REFERENCES image (id)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE item
  ADD CONSTRAINT fkjomcd7hhvl6l36mgb4rwa01w5 FOREIGN KEY (producer_id)
  REFERENCES producer (id)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE item_category
  ADD CONSTRAINT fkb00nakmw9p95imf42fpu3948y FOREIGN KEY (category_id)
  REFERENCES category (id)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE item_category
  ADD CONSTRAINT fklqjc8u9wq0w59oqhw60dw86s5 FOREIGN KEY (item_id)
  REFERENCES item (id)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE itemdetails
  ADD CONSTRAINT fkmj7i7pip4krc7dhch8idowlnc FOREIGN KEY (item_id)
  REFERENCES item (id)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE itemdetails_image
  ADD CONSTRAINT fkskce1wx21du16cedbhf3jlohf FOREIGN KEY (images_id)
  REFERENCES image (id)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE itemdetails_image
  ADD CONSTRAINT fkcqpkvkjurqbq34ieh7f49bwvo FOREIGN KEY (itemdetails_id)
  REFERENCES itemdetails (id)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE itemquantity
  ADD CONSTRAINT fkfsobtkbmkfxkxlit1lfn7q3cu FOREIGN KEY (item_id)
  REFERENCES item (id)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE itemquantity
  ADD CONSTRAINT fk6vknl2m714beusu1uyeqj0ghc FOREIGN KEY (orderdetails_id)
  REFERENCES orderdetails (id)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE orderdetails
  ADD CONSTRAINT fk73i6yle3sw7byge9vdc5l991d FOREIGN KEY (address_id)
  REFERENCES address (id)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE orderdetails
  ADD CONSTRAINT fk9apxoaew427qtq01af4e974j2 FOREIGN KEY (userentity_id)
  REFERENCES userentity (id)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE producer
  ADD CONSTRAINT fkbys83yrqd6lk532iw50bkolj4 FOREIGN KEY (image_id)
  REFERENCES image (id)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE producerdetails
  ADD CONSTRAINT fkp0lw3c0vlnxmjihsnsv7h0hte FOREIGN KEY (producer_id)
  REFERENCES producer (id)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE userentity_permissions
  ADD CONSTRAINT fklq8nprkjk8ryvmvvdmf1dh6ji FOREIGN KEY (userentity_id)
  REFERENCES userentity (id)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;


COMMIT;
